### ISSUE TITLE
How to use the library. 

### ISSUE THREAD

**Issue by hi2rashid** [bertugfahriozer/ci4mongodblibrary#1]
Steps I followed.

composer require bertugfahriozer/ci4mongodblibrary

Added the config file to app/config/MongoConfig.php

How to access the mongo db and query the collections and return in controller?

![image](https://user-images.githubusercontent.com/10250923/147384387-22b5f4b6-df9e-4186-9da8-f71c3035a62d.png)
When i do this i am getting the error

![image](https://user-images.githubusercontent.com/10250923/147384398-49eb812c-f8e8-4b67-9841-c9ccf80cc1b0.png)

**Comment by bertugfahriozer** [comment]
Hello @hi2rashid ,
You should use name space:
use ci4mongodblibrary\Models\CommonModel;

Sorry aboutreadme file. Last 2 month so hard for me i forgetted update readme file. But now updated. Thank you for your question.
