### ISSUE TITLE
Merhaba

### ISSUE THREAD

**Issue by mehmetsarr** [bertugfahriozer/ci4mongodblibrary#2]
Hocam, merhaba kütüphane için teşekkür ederim. Crud işlemleri için bilgi de verebilir misiniz?

**Comment by bertugfahriozer** [comment]
Merhaba,

https://github.com/ci4-cms-erp/ci4ms-mongodb/blob/dev/modules/Backend/Controllers/Tags.php 

Yukarıdaki linkte bütün örnekleri görebilirsiniz ek olarak alttaki model dosyası linkini inceleyebilirsiniz.

https://github.com/bertugfahriozer/ci4mongodblibrary/blob/master/app/Models/CommonModel.php
